### ISSUE TITLE
Найти API сервис для получения случайных шуток

### ISSUE THREAD

**Issue by TiberiumPY** [TiberiumPY/LOLBot#11]

**Comment by XenoAura** [comment]
http://www.umori.li/api
http://www.rzhunemogu.ru/FAQ.aspx
http://nextjoke.net/Api/Widget

**Comment by TiberiumPY** [comment]
@XenoAura на первом не получается - одни и те же результаты приходят, хоть random и указан
третье - виджет, а второе вроде подходит, спасибо

**Comment by BlayzerQ** [comment]
На bash.im можно, но через jsoup
