### ISSUE TITLE
Ошибка синтаксиса

### ISSUE THREAD

**Issue by CorpOfHack** [TiberiumPY/LOLBot#4]
Команда:
`python3 lolbot.py`

Ошибка:
 File "lolbot.py", line 230
    who = f"{'конференции' if data.conf else 'ЛС'} {data.peer_id}"
                                                                 ^
SyntaxError: invalid syntax

**Comment by TiberiumPY** [comment]
Нужен Python 3.6

**Comment by TiberiumPY** [comment]
@CorpOfHack нужен Python 3.6
Если нужна поддержка - пиши в vk.com/tiberium_1111
