### ISSUE TITLE
Защита от спамеров и недоброжелателей 

### ISSUE THREAD

**Issue by Volcharka** [TiberiumPY/LOLBot#8]
Реализовать защиту от ссылок в плагине msg_sender.py, т.к. любой может отправить ссылку на сайт, который находится в чёрном списке ВК,  и аккаунт бота, отправляя эту ссылку, получает бан.

**Comment by TiberiumPY** [comment]
Сделано в https://github.com/TiberiumPY/LOLBot/commit/f7302a5f45da6382e29d5d590958f949987b4dcf
Если будут ошибки с этим методов, создавайте ещё issues

**Comment by TiberiumPY** [comment]
https://github.com/TiberiumPY/LOLBot/commit/8e00e7d73d5833bf05e16a08b917c2225166a92b
Любые ссылки запрещены
